name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.10
        auto-update-conda: true
        miniforge-variant: Mambaforge
        miniforge-version: latest

    - name: Create and activate Conda environment
      run: |
        conda env create --file environment.yml
        echo "conda activate myenv" >> ~/.bashrc
        source ~/.bashrc

    - name: Install dependencies
      run: |
        conda install -n myenv flake8 pytest --yes

    - name: Lint with flake8
      run: |
        conda run -n myenv flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        conda run -n myenv flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: conda run -n myenv pytest
